---
title: الوحدات والإحداثيات ثلاثية الأبعاد في Unity
hero_image: images/banner.png
description: الوحدات والإحداثيات ثلاثية الأبعاد في Unity
version: 4
listed: false
copyedit: false
last_tested: "2021-10-19"
steps:
  - title: الوحدات والإحداثيات ثلاثية الأبعاد في Unity
